Added Makefile.conf.Linux, modified configure and Makefile, so that global_angupdate can be compiled on jet

diff --git a/util/global_angupdate/configure b/util/global_angupdate/configure
--- a/util/global_angupdate/configure
+++ b/util/global_angupdate/configure
@@ -38,14 +38,22 @@ if [ "$type" = "clean" ]; then
 fi
 
 
+# Set makeconf based on user input
+# ---------------------------------------
+makeconf="Makefile.conf.$type"
+
+
 # Node specific configuration
 # ---------------------------------------
-makeconf="Makefile.conf.`uname -n | awk '{print $1}'`"
+if [ ! -r ${makeconf} ]; then
+  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
+  makeconf="Makefile.conf.`uname -n | awk '{print $1}'`"
+fi  
 
 # Machine specific
 # ----------------
 if [ ! -r ${makeconf} ]; then
-  echo "$c: not using site specific ${makeconf} in `pwd`" 1>&2
+  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
   machine="`uname -m | awk '{print $1}'`"
   machine=`echo $machine | tr "[a-z]" "[A-Z]"`
   compiler=$F90
@@ -56,14 +64,8 @@ fi
 # Site specific configuration
 # ---------------------------
 if [ ! -r ${makeconf} ]; then
-#  echo "$c: cannot find site specific ${makeconf}" 1>&2
+  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
   makeconf="Makefile.conf.`uname -s | awk '{print $1}'`"
-  # if all are failed, make a simple one
-  # ---------------------------------------
-#  if [ `uname -s` = "AIX" ]; then
-#    echo "Linking Makefile to makefile" 1>&2
-#    ln -sf Makefile makefile
-#  fi
 fi
 
 # if the OS is UNICOS, it does not follow the convention
@@ -76,17 +78,12 @@ if [ ! -r ${makeconf} ]; then
   fi
 fi
 
-# if all are failed, make a simple one
-# ---------------------------------------
-if [ ! -r ${makeconf} ]; then
-  echo "$c: cannot find ${makeconf} in `pwd` " 1>&2
-  makeconf="Makefile.conf.$type"
-  if [ ! -r ${makeconf} ]; then
-    touch ${makeconf}
-  fi
+# Create soft link for Makefile.conf
+# ------------------------------------------------------
+if [ -r Makefile.conf ]; then
+   echo "$c:  remove Makefile.conf" 1>&2
+   rm Makefile.conf
 fi
-
-rm -f Makefile.conf
 ln -s ${makeconf} Makefile.conf
 
 echo "$c: using ${makeconf} in `pwd`" 1>&2
