Trunk: Merged EXP-port at r18975 to the trunk.
This change is the result of EMC's initial changes for improved porting of the code to Zeus.  The changes are intended to make running on Zeus possible and the transition to other machines more straightforward.  Note the these changes, also include bugs or inconsistencies in the code that were found in the process.  Also note, that these changes will probably not be the final changes.  These changes did not include the final fixes for all OPENMP problems, additional optimizations are possible and has not been tested on Zeus for all regression tests (they have been tested on the IBM for all regression tests), since not all regression tests have been ported. The update includes regression test modifications to make the GDAS and NMMB regression tests work on Zeus.

The regression tests have been performed on this version and all results verified.  The only changes result from fixing a bug in the combine_radobs routine which would have allowed different results using different sets of observations when the criterion is the same on multiple processors.  The fix removes the possibility of different results, but may change results when this situation occurs.  This does change results in several of the EMC regression tests.  Also, moving the 0.001 multiplication from ratio_errors to the ramp variable if l_sfcobserror_ramp_q is true.  This will also affect results for all EMC regression tests.

Please read ticket #247 for details

diff --git a/util/global_angupdate/configure b/util/global_angupdate/configure
--- a/util/global_angupdate/configure
+++ b/util/global_angupdate/configure
@@ -38,22 +38,14 @@ if [ "$type" = "clean" ]; then
 fi
 
 
-# Set makeconf based on user input
-# ---------------------------------------
-makeconf="Makefile.conf.$type"
-
-
 # Node specific configuration
 # ---------------------------------------
-if [ ! -r ${makeconf} ]; then
-  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
-  makeconf="Makefile.conf.`uname -n | awk '{print $1}'`"
-fi  
+makeconf="Makefile.conf.`uname -n | awk '{print $1}'`"
 
 # Machine specific
 # ----------------
 if [ ! -r ${makeconf} ]; then
-  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
+  echo "$c: not using site specific ${makeconf} in `pwd`" 1>&2
   machine="`uname -m | awk '{print $1}'`"
   machine=`echo $machine | tr "[a-z]" "[A-Z]"`
   compiler=$F90
@@ -64,8 +56,14 @@ fi
 # Site specific configuration
 # ---------------------------
 if [ ! -r ${makeconf} ]; then
-  echo "$c: cannot find ${makeconf} in `pwd`" 1>&2
+#  echo "$c: cannot find site specific ${makeconf}" 1>&2
   makeconf="Makefile.conf.`uname -s | awk '{print $1}'`"
+  # if all are failed, make a simple one
+  # ---------------------------------------
+#  if [ `uname -s` = "AIX" ]; then
+#    echo "Linking Makefile to makefile" 1>&2
+#    ln -sf Makefile makefile
+#  fi
 fi
 
 # if the OS is UNICOS, it does not follow the convention
@@ -78,12 +76,17 @@ if [ ! -r ${makeconf} ]; then
   fi
 fi
 
-# Create soft link for Makefile.conf
-# ------------------------------------------------------
-if [ -r Makefile.conf ]; then
-   echo "$c:  remove Makefile.conf" 1>&2
-   rm Makefile.conf
+# if all are failed, make a simple one
+# ---------------------------------------
+if [ ! -r ${makeconf} ]; then
+  echo "$c: cannot find ${makeconf} in `pwd` " 1>&2
+  makeconf="Makefile.conf.$type"
+  if [ ! -r ${makeconf} ]; then
+    touch ${makeconf}
+  fi
 fi
+
+rm -f Makefile.conf
 ln -s ${makeconf} Makefile.conf
 
 echo "$c: using ${makeconf} in `pwd`" 1>&2
